### ISSUE TITLE
Small issue in key name

### ISSUE THREAD

**Issue by edwardmp** [BasouKazuma/fastlane-plugin-lokalise#5]
Hi,

Great work on this plugin! Noticed a small issue: the `key_name` for iOS is defined as `key_ios`, but I noticed in the response it is actually just `key`. This might also apply for Android, but I wasn't able to verify this myself.

The issue concerns [this line](https://github.com/BasouKazuma/fastlane-plugin-lokalise/blob/13ccf37096db604eff198d17e59cfe113302f4b9/lib/fastlane/plugin/lokalise/actions/lokalise_metadata_action.rb#L271).

**Comment by BasouKazuma** [comment]
Odd, for me the request returns a few different types of key names (as you can see below) which was why I changed it from how it was originally handled in the old actions project. Maybe the API acts different based on project or region?
```"key_ios"=>"appstore.app.description", "key_android"=>"appstore.app.description", "key_web"=>"appstore.app.description", "key_other"=>"appstore.app.description"```

Though this plugin is still using the same `string/list` endpoint from the deprecated API that the original actions repo used.
https://lokalise.co/apidocs

In the new API the key names are also split up by platform as follows using the `/projects/{project_id}/keys` endpoint:
https://lokalise.co/api2docs
```
"key_name": {
     "ios": "index_welcome",
     "android": "indexWelcome",
    "web": "index.welcome",
    "other": "welcome-index"
}
```

Possibly migrating to the new API will resolve this inconsistency ...

**Comment by BasouKazuma** [comment]
I verified that it is handled differently based on how the Lokalise Project is set up. So I will make a different PR with a fix to fall back if the platform specific key does not exist and I'll add in the extra language mappings you had.

**Comment by BasouKazuma** [comment]
This should be all good to go now in version 2.0.6!

**Comment by edwardmp** [comment]
hi @BasouKazuma, thanks for looking into this!

My PR also included some other improvements (ability to set a few options). Could you merge that in? Or do you want a separate PR for that?

**Comment by BasouKazuma** [comment]
Didn't get a chance to fully look at that yet unfortunately so I just focused on the bug. I think it may be better to allow the user to pass in custom parameters so it can handle all types of request signatures. I'll take another look this week but feel free to open a new issue or PR.

**Comment by edwardmp** [comment]
@BasouKazuma 
Yes the other commits in the PR allows the user to specify additional API options. Please take a look at it if you have a chance, thanks.
